from collections.abc import Callable, Sequence

class Choice:
        def __init__(self, title: str, value: object = None) -> None: ...

class Separator:
        def __init__(self, line: str = "") -> None: ...

class Question:
        def ask(self) -> object: ...

def checkbox(message: str, choices: Sequence[object]) -> Question: ...
def text(
        message: str, validate: Callable[[str], bool | str] | None = None
) -> Question: ...
