# stubs/nbtlib/__init__.pyi
"""Type stubs for the nbtlib package (minimal, Any-free)."""

from collections.abc import Iterator
from pathlib import Path

class Base:
        def unpack(self, _json: bool = False) -> object: ...
        def __int__(self) -> int: ...

class Byte(Base): 
        def __init__(self, _value: int = 0) -> None: ...
class Short(Base): 
        def __init__(self, _value: int = 0) -> None: ...
class Int(Base): 
        def __init__(self, _value: int = 0) -> None: ...
class Long(Base): 
        def __init__(self, _value: int = 0) -> None: ...
class Float(Base): 
        def __init__(self, _value: float = 0.0) -> None: ...
class Double(Base): 
        def __init__(self, _value: float = 0.0) -> None: ...
class String(Base): 
        def __init__(self, _value: str = "") -> None: ...

class List(Base):
        def __getitem__(self, _index: int) -> object: ...
        def __setitem__(self, _index: int, _value: object) -> None: ...
        def __delitem__(self, _index: int) -> None: ...
        def __len__(self) -> int: ...
        def __iter__(self) -> Iterator[object]: ...
        def __contains__(self, _item: object) -> bool: ...

class Compound(Base):
        def __init__(self, _mapping: dict[str, object] | None = None) -> None: ...
        def get(self, _key: str, _default: object = None) -> object: ...
        def __getitem__(self, _key: str) -> object: ...
        def __setitem__(self, _key: str, _value: object) -> None: ...
        def __delitem__(self, _key: str) -> None: ...
        def __contains__(self, _key: str) -> bool: ...
        def __iter__(self) -> Iterator[str]: ...
        def keys(self) -> list[str]: ...
        def values(self) -> list[object]: ...
        def items(self) -> list[tuple[str, object]]: ...

class ByteArray(Base): ...
class IntArray(Base): ...
class LongArray(Base): ...

class File(Compound):
        def write(self, _fileobj: object) -> None: ...
        def save(
                self,
                _filename: str | Path | None = None,
                _gzipped: bool | None = None,
                _byteorder: str = "big",
        ) -> None: ...
        @classmethod
        def parse(cls, _fileobj: object, _byteorder: str = "big") -> File: ...

def load(
        _filename: str | Path,
        _gzipped: bool | None = None,
        _byteorder: str = "big",
) -> File: ...
def parse_nbt(_data: str) -> object: ...
